// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 10/1/2024, 2:59:12 PM
const configMerger = require("/Users/macbook_pro_16/Desktop/personal-website/node_modules/@nuxtjs/tailwindcss/dist/runtime/merger.js");

const inlineConfig = {"content":[],"theme":{"extend":{}},"plugins":[]};

const config = [
require("./../tailwind.config.js")
].reduce((prev, curr) => configMerger(curr, prev), configMerger(inlineConfig, { content: ["/Users/macbook_pro_16/Desktop/personal-website/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/macbook_pro_16/Desktop/personal-website/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/macbook_pro_16/Desktop/personal-website/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/macbook_pro_16/Desktop/personal-website/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/macbook_pro_16/Desktop/personal-website/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/macbook_pro_16/Desktop/personal-website/plugins/**/*.{js,ts,mjs}","/Users/macbook_pro_16/Desktop/personal-website/composables/**/*.{js,ts,mjs}","/Users/macbook_pro_16/Desktop/personal-website/utils/**/*.{js,ts,mjs}","/Users/macbook_pro_16/Desktop/personal-website/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/macbook_pro_16/Desktop/personal-website/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/macbook_pro_16/Desktop/personal-website/app.config.{js,ts,mjs}"] }));

module.exports = config
